@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "main.Main#main(String[])",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "main.Main",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_1950800714 { 
   	label=repository
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1055222969 { 
   	label=UserRepository
	labeljust=l
	fillcolor=white
	style=filled
   
   UserRepository1950800714XXXfindAll0[
	label="+ findAll()"
	style=filled
	fillcolor=white
	tooltip="UserRepository

null"
	fontcolor=darkgreen
];

UserRepository1950800714XXXfindById104431[
	label="+ findById()"
	style=filled
	fillcolor=white
	tooltip="UserRepository

null"
	fontcolor=darkgreen
];

UserRepository1950800714XXXfindByUsername1808118735[
	label="+ findByUsername()"
	style=filled
	fillcolor=white
	tooltip="UserRepository

null"
	fontcolor=darkgreen
];

UserRepository1950800714XXXsave2645995[
	label="+ save()"
	style=filled
	fillcolor=white
	tooltip="UserRepository

null"
	fontcolor=darkgreen
];

UserRepository1950800714XXXupdate2645995[
	label="+ update()"
	style=filled
	fillcolor=white
	tooltip="UserRepository

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1417493114 { 
   	label=CarRepository
	labeljust=l
	fillcolor=white
	style=filled
   
   CarRepository1950800714XXXdeleteById104431[
	label="+ deleteById()"
	style=filled
	fillcolor=white
	tooltip="CarRepository

null"
	fontcolor=darkgreen
];

CarRepository1950800714XXXfindAll0[
	label="+ findAll()"
	style=filled
	fillcolor=white
	tooltip="CarRepository

null"
	fontcolor=darkgreen
];

CarRepository1950800714XXXfindById104431[
	label="+ findById()"
	style=filled
	fillcolor=white
	tooltip="CarRepository

null"
	fontcolor=darkgreen
];

CarRepository1950800714XXXsave67508[
	label="+ save()"
	style=filled
	fillcolor=white
	tooltip="CarRepository

null"
	fontcolor=darkgreen
];

CarRepository1950800714XXXupdate67508[
	label="+ update()"
	style=filled
	fillcolor=white
	tooltip="CarRepository

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_254775924 { 
   	label=OrderRepository
	labeljust=l
	fillcolor=white
	style=filled
   
   OrderRepository1950800714XXXfindAll0[
	label="+ findAll()"
	style=filled
	fillcolor=white
	tooltip="OrderRepository

&#10;  Returns a list of all orders.&#10; &#10;  @return the list of orders&#10; "
	fontcolor=darkgreen
];

OrderRepository1950800714XXXfindById104431[
	label="+ findById()"
	style=filled
	fillcolor=white
	tooltip="OrderRepository

null"
	fontcolor=darkgreen
];

OrderRepository1950800714XXXsave76453678[
	label="+ save()"
	style=filled
	fillcolor=white
	tooltip="OrderRepository

&#10;  Saves an order to the repository.&#10; &#10;  @param order the order to save&#10; "
	fontcolor=darkgreen
];

OrderRepository1950800714XXXupdate76453678[
	label="+ update()"
	style=filled
	fillcolor=white
	tooltip="OrderRepository

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_324606657 { 
   	label=AuditRepository
	labeljust=l
	fillcolor=white
	style=filled
   
   AuditRepository1950800714XXXfindAll0[
	label="+ findAll()"
	style=filled
	fillcolor=white
	tooltip="AuditRepository

&#10;  Returns a list of all audit log entries.&#10; &#10;  @return the list of audit log entries&#10; "
	fontcolor=darkgreen
];
} 
} 

subgraph cluster_1984153269 { 
   	label=service
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1292461713 { 
   	label=UserService
	labeljust=l
	fillcolor=white
	style=filled
   
   UserService1984153269XXXaddUser2645995[
	label="+ addUser()"
	style=filled
	fillcolor=white
	tooltip="UserService

null"
	fontcolor=darkgreen
];

UserService1984153269XXXupdateUserRole316174756[
	label="+ updateUserRole()"
	style=filled
	fillcolor=white
	tooltip="UserService

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1322241299 { 
   	label=AuditService
	labeljust=l
	fillcolor=white
	style=filled
   
   AuditService1984153269XXXlogAction471814256[
	label="+ logAction()"
	style=filled
	fillcolor=white
	tooltip="AuditService

&#10;  Logs an action performed by a user.&#10; &#10;  @param user the user who performed the action&#10;  @param action the action performed by the user&#10; "
	fontcolor=darkgreen
];
} 

subgraph cluster_1953981356 { 
   	label=SearchService
	labeljust=l
	fillcolor=white
	style=filled
   
   SearchService1984153269XXXfilterLogs2057577392[
	label="+ filterLogs()"
	style=filled
	fillcolor=white
	tooltip="SearchService

&#10;  Returns a list of audit log entries filtered by date, user, and action type.&#10; &#10;  @param startDate the start date for filtering&#10;  @param endDate the end date for filtering&#10;  @param user the user to filter by (can be null)&#10;  @param actionthe action type to filter by (can be null)&#10;  @return the list of filtered audit log entries&#10; "
	fontcolor=darkgreen
];

SearchService1984153269XXXfilterUsersByRole1808118735[
	label="+ filterUsersByRole()"
	style=filled
	fillcolor=white
	tooltip="SearchService

null"
	fontcolor=darkgreen
];

SearchService1984153269XXXfindByUsername1808118735[
	label="+ findByUsername()"
	style=filled
	fillcolor=white
	tooltip="SearchService

null"
	fontcolor=darkgreen
];

SearchService1984153269XXXgetPurchaseCount104431[
	label="+ getPurchaseCount()"
	style=filled
	fillcolor=white
	tooltip="SearchService

&#10;  Gets the purchase count for a user. should be updated to stream&#10; &#10;  @param userId the ID of the user&#10;  @return the number of purchases made by the user&#10; "
	fontcolor=darkgreen
];

SearchService1984153269XXXsearchCars1067204025[
	label="+ searchCars()"
	style=filled
	fillcolor=white
	tooltip="SearchService

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_497055430 { 
   	label=CarService
	labeljust=l
	fillcolor=white
	style=filled
   
   CarService1984153269XXXaddCar67508[
	label="+ addCar()"
	style=filled
	fillcolor=white
	tooltip="CarService

null"
	fontcolor=darkgreen
];

CarService1984153269XXXdeleteCar104431[
	label="+ deleteCar()"
	style=filled
	fillcolor=white
	tooltip="CarService

null"
	fontcolor=darkgreen
];

CarService1984153269XXXgetById104431[
	label="+ getById()"
	style=filled
	fillcolor=white
	tooltip="CarService

null"
	fontcolor=darkgreen
];

CarService1984153269XXXupdateCar67508[
	label="+ updateCar()"
	style=filled
	fillcolor=white
	tooltip="CarService

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_620451264 { 
   	label=OrderService
	labeljust=l
	fillcolor=white
	style=filled
   
   OrderService1984153269XXXcancelOrder104431[
	label="+ cancelOrder()"
	style=filled
	fillcolor=white
	tooltip="OrderService

&#10;  Cancel Order&#10;  @param orderId&#10; "
	fontcolor=darkgreen
];

OrderService1984153269XXXcreateOrder515322732[
	label="+ createOrder()"
	style=filled
	fillcolor=white
	tooltip="OrderService

&#10;  Creates a new order.&#10; &#10;  @param carId the ID of the car to order&#10;  @param customerId the ID of the customer placing the order&#10;  @return the created order&#10; "
	fontcolor=darkgreen
];

OrderService1984153269XXXupdateOrderStatus854034237[
	label="+ updateOrderStatus()"
	style=filled
	fillcolor=white
	tooltip="OrderService

&#10;  Update Order&#10;  @param orderId&#10;  @param status&#10; "
	fontcolor=darkgreen
];
} 

subgraph cluster_888476180 { 
   	label=AuthService
	labeljust=l
	fillcolor=white
	style=filled
   
   AuthService1984153269XXXlogin2013066710[
	label="+ login()"
	style=filled
	fillcolor=white
	tooltip="AuthService

null"
	fontcolor=darkgreen
];

AuthService1984153269XXXregister2013066710[
	label="+ register()"
	style=filled
	fillcolor=white
	tooltip="AuthService

null"
	fontcolor=darkgreen
];

AuthService1984153269XXXregisterAdmin2013066710[
	label="+ registerAdmin()"
	style=filled
	fillcolor=white
	tooltip="AuthService

null"
	fontcolor=darkgreen
];
} 
} 

subgraph cluster_3343801 { 
   	label=main
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_297445138 { 
   	label=Main
	labeljust=l
	fillcolor=white
	style=filled
   
   Main3343801XXXmain1859653459[
	label="+ main()"
	style=filled
	fillcolor=white
	tooltip="Main

null"
	penwidth=4
	fontcolor=darkgreen
];
} 
} 

subgraph cluster_3365 { 
   	label=in
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1057255888 { 
   	label=UserController
	labeljust=l
	fillcolor=white
	style=filled
   
   UserController3365XXXaddUser0[
	label="+ addUser()"
	style=filled
	fillcolor=white
	tooltip="UserController

null"
	fontcolor=darkgreen
];

UserController3365XXXchangeUserRole0[
	label="+ changeUserRole()"
	style=filled
	fillcolor=white
	tooltip="UserController

null"
	fontcolor=darkgreen
];

UserController3365XXXlistUsers0[
	label="+ listUsers()"
	style=filled
	fillcolor=white
	tooltip="UserController

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1064253089 { 
   	label=OrderController
	labeljust=l
	fillcolor=white
	style=filled
   
   OrderController3365XXXcancelOrder0[
	label="+ cancelOrder()"
	style=filled
	fillcolor=white
	tooltip="OrderController

null"
	fontcolor=darkgreen
];

OrderController3365XXXcreateOrder104431[
	label="+ createOrder()"
	style=filled
	fillcolor=white
	tooltip="OrderController

null"
	fontcolor=darkgreen
];

OrderController3365XXXlistOrders0[
	label="+ listOrders()"
	style=filled
	fillcolor=white
	tooltip="OrderController

null"
	fontcolor=darkgreen
];

OrderController3365XXXupdateOrderStatus0[
	label="+ updateOrderStatus()"
	style=filled
	fillcolor=white
	tooltip="OrderController

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_130541209 { 
   	label=CarController
	labeljust=l
	fillcolor=white
	style=filled
   
   CarController3365XXXaddCar0[
	label="+ addCar()"
	style=filled
	fillcolor=white
	tooltip="CarController

null"
	fontcolor=darkgreen
];

CarController3365XXXdeleteCar0[
	label="+ deleteCar()"
	style=filled
	fillcolor=white
	tooltip="CarController

null"
	fontcolor=darkgreen
];

CarController3365XXXlistCars0[
	label="+ listCars()"
	style=filled
	fillcolor=white
	tooltip="CarController

null"
	fontcolor=darkgreen
];

CarController3365XXXupdateCar0[
	label="+ updateCar()"
	style=filled
	fillcolor=white
	tooltip="CarController

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_422605677 { 
   	label=AuthController
	labeljust=l
	fillcolor=white
	style=filled
   
   AuthController3365XXXlogin0[
	label="+ login()"
	style=filled
	fillcolor=white
	tooltip="AuthController

null"
	fontcolor=darkgreen
];

AuthController3365XXXregister0[
	label="+ register()"
	style=filled
	fillcolor=white
	tooltip="AuthController

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_993977043 { 
   	label=SearchController
	labeljust=l
	fillcolor=white
	style=filled
   
   SearchController3365XXXexportLogs0[
	label="+ exportLogs()"
	style=filled
	fillcolor=white
	tooltip="SearchController

null"
	fontcolor=darkgreen
];

SearchController3365XXXfilterAuditLogs0[
	label="+ filterAuditLogs()"
	style=filled
	fillcolor=white
	tooltip="SearchController

null"
	fontcolor=darkgreen
];

SearchController3365XXXfilterUsersByRole0[
	label="+ filterUsersByRole()"
	style=filled
	fillcolor=white
	tooltip="SearchController

null"
	fontcolor=darkgreen
];

SearchController3365XXXsearchCars0[
	label="+ searchCars()"
	style=filled
	fillcolor=white
	tooltip="SearchController

null"
	fontcolor=darkgreen
];

SearchController3365XXXsortUsersByPurchases0[
	label="+ sortUsersByPurchases()"
	style=filled
	fillcolor=white
	tooltip="SearchController

null"
	fontcolor=darkgreen
];
} 
} 

'edges    
AuthController3365XXXlogin0 -> AuthService1984153269XXXlogin2013066710;
AuthController3365XXXregister0 -> AuthService1984153269XXXregister2013066710;
AuthService1984153269XXXlogin2013066710 -> UserRepository1950800714XXXfindByUsername1808118735;
AuthService1984153269XXXregister2013066710 -> AuditService1984153269XXXlogAction471814256;
AuthService1984153269XXXregister2013066710 -> UserRepository1950800714XXXfindByUsername1808118735;
AuthService1984153269XXXregister2013066710 -> UserRepository1950800714XXXsave2645995;
AuthService1984153269XXXregisterAdmin2013066710 -> UserRepository1950800714XXXsave2645995;
CarController3365XXXaddCar0 -> CarService1984153269XXXaddCar67508;
CarController3365XXXdeleteCar0 -> CarService1984153269XXXdeleteCar104431;
CarController3365XXXupdateCar0 -> CarService1984153269XXXgetById104431;
CarController3365XXXupdateCar0 -> CarService1984153269XXXupdateCar67508;
CarService1984153269XXXaddCar67508 -> CarRepository1950800714XXXsave67508;
CarService1984153269XXXdeleteCar104431 -> CarRepository1950800714XXXdeleteById104431;
CarService1984153269XXXgetById104431 -> CarRepository1950800714XXXfindById104431;
CarService1984153269XXXupdateCar67508 -> CarRepository1950800714XXXupdate67508;
Main3343801XXXmain1859653459 -> AuthController3365XXXlogin0;
Main3343801XXXmain1859653459 -> AuthController3365XXXregister0;
Main3343801XXXmain1859653459 -> AuthService1984153269XXXregisterAdmin2013066710;
Main3343801XXXmain1859653459 -> CarController3365XXXaddCar0;
Main3343801XXXmain1859653459 -> CarController3365XXXdeleteCar0;
Main3343801XXXmain1859653459 -> CarController3365XXXlistCars0;
Main3343801XXXmain1859653459 -> CarController3365XXXupdateCar0;
Main3343801XXXmain1859653459 -> OrderController3365XXXcancelOrder0;
Main3343801XXXmain1859653459 -> OrderController3365XXXcreateOrder104431;
Main3343801XXXmain1859653459 -> OrderController3365XXXlistOrders0;
Main3343801XXXmain1859653459 -> OrderController3365XXXupdateOrderStatus0;
Main3343801XXXmain1859653459 -> SearchController3365XXXexportLogs0;
Main3343801XXXmain1859653459 -> SearchController3365XXXfilterAuditLogs0;
Main3343801XXXmain1859653459 -> SearchController3365XXXfilterUsersByRole0;
Main3343801XXXmain1859653459 -> SearchController3365XXXsearchCars0;
Main3343801XXXmain1859653459 -> SearchController3365XXXsortUsersByPurchases0;
Main3343801XXXmain1859653459 -> UserController3365XXXaddUser0;
Main3343801XXXmain1859653459 -> UserController3365XXXchangeUserRole0;
Main3343801XXXmain1859653459 -> UserController3365XXXlistUsers0;
OrderController3365XXXcancelOrder0 -> OrderService1984153269XXXcancelOrder104431;
OrderController3365XXXcreateOrder104431 -> OrderService1984153269XXXcreateOrder515322732;
OrderController3365XXXupdateOrderStatus0 -> OrderService1984153269XXXupdateOrderStatus854034237;
OrderService1984153269XXXcancelOrder104431 -> AuditService1984153269XXXlogAction471814256;
OrderService1984153269XXXcancelOrder104431 -> CarRepository1950800714XXXupdate67508;
OrderService1984153269XXXcancelOrder104431 -> OrderRepository1950800714XXXfindById104431;
OrderService1984153269XXXcancelOrder104431 -> OrderRepository1950800714XXXupdate76453678;
OrderService1984153269XXXcreateOrder515322732 -> AuditService1984153269XXXlogAction471814256;
OrderService1984153269XXXcreateOrder515322732 -> CarRepository1950800714XXXfindById104431;
OrderService1984153269XXXcreateOrder515322732 -> CarRepository1950800714XXXupdate67508;
OrderService1984153269XXXcreateOrder515322732 -> OrderRepository1950800714XXXsave76453678;
OrderService1984153269XXXcreateOrder515322732 -> UserRepository1950800714XXXfindById104431;
OrderService1984153269XXXupdateOrderStatus854034237 -> AuditService1984153269XXXlogAction471814256;
OrderService1984153269XXXupdateOrderStatus854034237 -> CarRepository1950800714XXXupdate67508;
OrderService1984153269XXXupdateOrderStatus854034237 -> OrderRepository1950800714XXXfindById104431;
OrderService1984153269XXXupdateOrderStatus854034237 -> OrderRepository1950800714XXXupdate76453678;
SearchController3365XXXfilterAuditLogs0 -> SearchService1984153269XXXfilterLogs2057577392;
SearchController3365XXXfilterAuditLogs0 -> SearchService1984153269XXXfindByUsername1808118735;
SearchController3365XXXfilterUsersByRole0 -> SearchService1984153269XXXfilterUsersByRole1808118735;
SearchController3365XXXsearchCars0 -> SearchService1984153269XXXsearchCars1067204025;
SearchController3365XXXsortUsersByPurchases0 -> SearchService1984153269XXXgetPurchaseCount104431;
SearchService1984153269XXXfilterLogs2057577392 -> AuditRepository1950800714XXXfindAll0;
SearchService1984153269XXXfilterUsersByRole1808118735 -> UserRepository1950800714XXXfindAll0;
SearchService1984153269XXXfindByUsername1808118735 -> UserRepository1950800714XXXfindByUsername1808118735;
SearchService1984153269XXXgetPurchaseCount104431 -> OrderRepository1950800714XXXfindAll0;
SearchService1984153269XXXsearchCars1067204025 -> CarRepository1950800714XXXfindAll0;
UserController3365XXXaddUser0 -> UserService1984153269XXXaddUser2645995;
UserController3365XXXchangeUserRole0 -> UserService1984153269XXXupdateUserRole316174756;
UserService1984153269XXXaddUser2645995 -> UserRepository1950800714XXXsave2645995;
UserService1984153269XXXupdateUserRole316174756 -> UserRepository1950800714XXXfindById104431;
UserService1984153269XXXupdateUserRole316174756 -> UserRepository1950800714XXXupdate2645995;
    
}
@enduml